reward:
  shoot_enemy: 200
  remove_enemy: 1
  lose_life: -100
  finish_game: -2
  survive_frame: 0.1
  avoid_enemy: 2
  fast_kill_bonus: 100
  idle_penalty: -5
  edge_penalty: -10
  round_bonus: 500
  cleared_wave: 300
  missed_shot_penalty: -20
  formation_broken: 100
  row_broken: 50
  column_broken: 50
  cluster_broken: 75
  too_close_to_enemy: -100
  safe_distance: 10
  very_safe_distance: 20
  avoided_enemy: 5

agent:
  type: DoubleDQN
  per: true
  gamma: 0.99
  lr: 0.0001
  buffer_size: 1000000
  batch_size: 64
  epsilon_start: 1.0
  epsilon_min: 0.05
  epsilon_decay: 0.995
  update_target_steps: 1000
  checkpoint_interval: 1000
  stack_size: 4 